### ISSUE TITLE
Please can you provide documentation?

### ISSUE THREAD

**Issue by mkmk435** [JuanJMarques/pymetamorph#2]
Hi, i am a CS student and i want to do a thesis on metamorphic engines.
I find your code really interesting but it is a bit difficult to follow without any comment/documentation.

Also it gives a lot of errors with Capstone/Keystone so i did not manage to make it work.

Please if you can help me let me know. Opening an Issue was the only method i thought to write to you

**Comment by JuanJMarques** [comment]
Sorry but as you can see in the history this project is inactive since 8 years ago. I just didn't remeber to make as archived. 

About the Capstone/keystone libaries maybe is an incompatibility with the actual versions.

Sorry I couldn't help you but I haven't worked on metamorphic engines since I finished the project 8 years ago.
